apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: movies-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: http
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: movie-details
spec:
  hosts:
  - "*"
  gateways:
  - movies-gateway
  http:
  - match:
    - uri:
        exact: /movies/details
    route:
    - destination:
        host: movie-details
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: budget
spec:
  hosts:
  - "*"
  gateways:
  - movies-gateway
  http:
  - match:
    - uri:
        exact: /movies/budget
    route:
    - destination:
        host: budget
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: predictions
spec:
  hosts:
  - "*"
  gateways:
  - movies-gateway
  http:
  - match:
    - uri:
        exact: /movies/predictions
    route:
    - destination:
        host: predictions
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratings
spec:
  hosts:
  - "*"
  gateways:
  - movies-gateway
  http:
  - match:
    - uri:
        exact: /movies/ratings
    route:
    - destination:
        host: ratings
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: revenues
spec:
  hosts:
  - "*"
  gateways:
  - movies-gateway
  http:
  - match:
    - uri:
        exact: /movies/revenues
    route:
    - destination:
        host: revenues
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: popularity
spec:
  hosts:
  - "*"
  gateways:
  - movies-gateway
  http:
  - match:
    - uri:
        exact: /movies/popularity
    route:
    - destination:
        host: popularity
        port:
          number: 80