apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: neeraj-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - path: /movie-details
        backend:
          serviceName: movie-details
          servicePort: 80  