apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: movies-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
      - name: movies
        image: gcr.io/neeraj-arena/movies
        ports:
        - containerPort: 9002

---
kind: Service
apiVersion: v1
metadata:
  name: movies-service
spec:
  selector:
    app: movies
  ports:
  - protocol: TCP
    port: 9002
  type: ClusterIP