apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: neeraj-nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /info/details
        backend:
          serviceName: movie-details
          servicePort: 80
      - path: /info/budget
        backend:
          serviceName: budget
          servicePort: 80
      - path: /info/revenues
        backend:
          serviceName: revenues
          servicePort: 80
      - path: /info/popularity
        backend:
          serviceName: popularity
          servicePort: 80        
      - path: /info/ratings
        backend:
          serviceName: ratings
          servicePort: 80
      - path: /predictions/boxoffice
        backend:
          serviceName: predictions
          servicePort: 80              